# Generated by Django 4.1.5 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
