# Generated by Django 4.1.5 on 2023-01-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_commentmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comment',
        ),
    ]
